# Generated by Django 3.0.5 on 2020-06-28 06:58

import common.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelfattestUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('external_id', models.UUIDField(default=common.uuid.unique_uuid4, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('email', models.CharField(max_length=64, unique=True, verbose_name='email')),
                ('is_active', models.BooleanField(default=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'selfattest_user',
            },
        ),
        migrations.AddIndex(
            model_name='selfattestuser',
            index=models.Index(fields=['email'], name='selfattest__email_97eb44_idx'),
        ),
        migrations.AddIndex(
            model_name='selfattestuser',
            index=models.Index(fields=['external_id'], name='selfattest__externa_e5110a_idx'),
        ),
    ]
