FROM python:3.6.9-slim

ENV PYTHONUNBUFFERED 1

WORKDIR /selfattest_web/

RUN apt-get update

RUN apt-get -qq -y install binutils libproj-dev gdal-bin postgresql-client


RUN python -m pip install --upgrade pip


COPY requirements-dev.txt /selfattest_web/
RUN pip install -r requirements-dev.txt

COPY . /selfattest_web/
