FROM tutum/nginx


RUN sudo apt-get update && sudo apt-get --yes --force-yes install software-properties-common


RUN rm /etc/nginx/sites-enabled/default

# forward request and error logs to docker log collector
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
       && ln -sf /dev/stderr /var/log/nginx/error.log

COPY sites-enabled/prod/web_monolith /etc/nginx/sites-enabled

RUN mkdir -p /www/data
COPY sites-enabled/prod/index.html /www/data